Obligatorio-Cliente/Controllers/EspecieMarinaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Obligatorio_Cliente.Models;
using System.Data;
using System.Net.Http.Headers;
using System.Text;

namespace Obligatorio_Cliente.Controllers
{
    public class EspecieMarinaController : Controller
    {

        private HttpClient cliente = new HttpClient();
        private string url = "http://localhost:5155/api";
        private IWebHostEnvironment _environment;

        public EspecieMarinaController(IWebHostEnvironment environment)
        {
            _environment = environment;
        }
        // GET: EspecieMarinaController
        public ActionResult Index(string mensaje)
        {
            try
            {
                ViewBag.Logueado = HttpContext.Session.GetString("usuario");
                return View(GetEspeciesMarinas());

            }
            catch (Exception ex)
            {

                ViewBag.mensaje = ex.Message;
                return View();
            }
        }

        // GET: EspecieMarinaController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: EspecieMarinaController/Create
        public ActionResult Create()
        {
            try
            {
                if (HttpContext.Session.GetString("usuario") != null)
                {
                    IEnumerable<EcosistemaMarinoModel> ecosistemasMarinos = GetEcosistemaMarinos();
                    if (ecosistemasMarinos.Count() > 0)
                    {
                        ViewBag.EcosistemasMarinos = ecosistemasMarinos;
                    }
                    else
                    {
                        ViewBag.EcosistemasMarinos = null;
                    }
                    ViewBag.Amenazas = GetAmenazas();
                    ViewBag.EstadosConservacion = GetEstadosConservaciones();
                    return View();

                }
                else
                {
                    return RedirectToAction(nameof(Index));
                }

            }
            catch (Exception ex)
            {

                return RedirectToAction("Index", "Home");
            }
        }

        // POST: EspecieMarinaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EspecieMarinaModel especieMarina, List<IFormFile> imagen, List<int> SelectedOptions, int SelectedOptionEstado, List<int> SelectedOptionsAmenazas)
        {
            try
            {
                if (especieMarina == null || imagen.Count == 0 || SelectedOptions.Count == 0 || SelectedOptionEstado == 0 || SelectedOptionsAmenazas.Count == 0)
                {
                    return RedirectToAction(nameof(Create), new { mensaje = "Debe completar todos los campos" });
                }

                especieMarina.EcosistemaMarinos = new List<EcosistemaMarinoModel>();
                foreach (var id in SelectedOptions)
                {
                    EcosistemaMarinoModel ecosistemaMarino = obtenerEcosistemaMarinoPorId(id);
                    if (ecosistemaMarino != null)
                    {
                        especieMarina.EcosistemaMarinos.Add(ecosistemaMarino);
                    }

                }
                especieMarina.Amenazas = new List<AmenazasAsociadasModel>();
                foreach (var item in SelectedOptionsAmenazas)
                {
                    AmenazaModel amenaza = ObtenerAmenazaPorId(item);

                    if (amenaza != null)
                    {
                        AmenazasAsociadasModel amenazasAsociadas = new AmenazasAsociadasModel();
                        amenazasAsociadas.AmenazaId = amenaza.Id;
                        especieMarina.Amenazas.Add(amenazasAsociadas);
                    }
                }

                especieMarina.EstadoConservacionId = SelectedOptionEstado;
                EspecieMarinaModel especieMarinaModel = AltaEspecie(especieMarina);
                if (GuardarImagen(imagen, especieMarinaModel))
                {
                    UpdateEspecie(especieMarinaModel);

                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return RedirectToAction(nameof(Create), new { mensaje = "No se pudo guardar la imagen" });
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction(nameof(Create), new { mensaje = ex.Message });
            }
        }

        public ActionResult AsociarEspecieAEcosistema(string mensaje, int id)
        {
            try

            {
                if (HttpContext.Session.GetString("usuario") != null)
                {
                    List<EspecieEcosistemaModel> especieAsociarEcosistema = new List<EspecieEcosistemaModel>();
                    EspecieMarinaModel especieMarina = ObtenerEspeciePorId(id);
                    if (especieMarina != null)
                    {

                        TempData["idEspecie"] = especieMarina.Id;


                        foreach (EcosistemaMarinoModel item in especieMarina.EcosistemaMarinos)
                        {
                            if (item != null)
                            {
                                EspecieEcosistemaModel aux = new EspecieEcosistemaModel();
                                aux.ecosistemasMarinos = item;
                                especieAsociarEcosistema.Add(aux);

                            }

                        }
                        ViewBag.Mensaje = mensaje;
                        return View(especieAsociarEcosistema);

                    }
                    else
                    {
                        return RedirectToAction(nameof(AsociarEspecieAEcosistema), new { mensaje = "No se encontro la especie" });
                    }
                }
                else
                {
                    return RedirectToAction(nameof(Index));

                }
            }
            catch (Exception ex)
            {

                return RedirectToAction(nameof(AsociarEspecieAEcosistema), new { mensaje = ex.Message });
            }
        }

        [HttpPost]
        public ActionResult AsociarEspecieAEcosistema(int EcosistemaSeleccionado)
        {

            try
            {
                int idEspecie = (int)TempData["idEspecie"];
                EspecieMarinaModel especieMarina = ObtenerEspeciePorId(idEspecie);

                IEnumerable<EspecieMarinaModel> especieMarinas = BuscarEspeciesQueHabitanUnEcosistema(EcosistemaSeleccionado);
                if (especieMarinas != null)
                {
                    foreach (var item in especieMarinas)
                    {
                        if (item.Id == idEspecie)
                        {
                            return RedirectToAction(nameof(AsociarEspecieAEcosistema), new { mensaje = "La especie ya se encuentra asociada al ecosistema" });
                        }
                    }

                }

                EcosistemaMarinoModel ecosistemaMarino = obtenerEcosistemaMarinoPorId(EcosistemaSeleccionado);

                foreach (var item in ecosistemaMarino.Amenazas)
                {
                    foreach (var item1 in especieMarina.Amenazas)
                    {
                        if (item.AmenazaId == item1.AmenazaId)
                        {
                            return RedirectToAction(nameof(AsociarEspecieAEcosistema), new { mensaje = "La especie no puede habitar el ecosistema porque tiene amenazas en comun" });
                        }
                    }
                }
                //Ecosistema
                EstadoConservacionModel estadoConservacionEcosistema = ObtenerEstadoConservacionPorId((int)ecosistemaMarino.EstadoConservacionId);
                RangosModel rangosEcosistema = new RangosModel();
                rangosEcosistema.Minimo = estadoConservacionEcosistema.Rangos.Minimo;
                rangosEcosistema.Maximo = estadoConservacionEcosistema.Rangos.Maximo;

                //Especie
                EstadoConservacionModel estadoConservacionEspecie = ObtenerEstadoConservacionPorId((int)especieMarina.EstadoConservacionId);
                RangosModel rangosEspecie = new RangosModel();
                rangosEspecie.Minimo = estadoConservacionEspecie.Rangos.Minimo;
                rangosEspecie.Maximo = estadoConservacionEspecie.Rangos.Maximo;

                if (rangosEcosistema.Minimo < rangosEspecie.Minimo)
                {
                    return RedirectToAction(nameof(AsociarEspecieAEcosistema), new { mensaje = "La especie no puede habitar el ecosistema porque el estado de conservacion del ecosistema es menor al de la especie" });
                }

                AsociarEspecieModel asociar = new AsociarEspecieModel();
                asociar.EcosistemaSeleccionado = EcosistemaSeleccionado;
                asociar.IdEspecie = idEspecie;
                AsociarEspecieAEcosistema(asociar);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                return RedirectToAction(nameof(AsociarEspecieAEcosistema), new { mensaje = ex.Message });
            }
        }






        // GET: EspecieMarinaController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: EspecieMarinaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EspecieMarinaController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();

Obligatorio-Cliente/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Obligatorio_Cliente</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Obligatorio_Cliente.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Obligatorio_Cliente</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (Context.Session.GetString("usuario") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                            //El logueado es el admin
                            @if (Context.Session.GetString("LogueadoRol") == "admin")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Create">Crear un usuario</a>
                                </li>
                            }
                            //Cuando hay un usuario logueado

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Configuracion" asp-action="Index">Configuraciones</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="EcosistemaMarino" asp-action="Create">Crear ecosistema</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="EspecieMarina" asp-action="Create">Crear especie</a>
                            </li>


                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="EspecieMarina" asp-action="BuscarEspeciesEnPeligroDeExtincion">Especies en Peligro de Extincion</a>
                            </li>


                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="EspecieMarina" asp-action="BuscarEspeciesQueHabitanEcosistema">Buscar especies que habitan un ecosistema</a>
                            </li>


                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="EspecieMarina" asp-action="BuscarEcosistemasMarinosNoPuedenHabitarEspecie">Buscar ecosistemas marinos que no pueden habitar una especie</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="EspecieMarina" asp-action="BuscarPorNombreCientifico">Buscar especie por nombre cientifico</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="EspecieMarina" asp-action="BuscarPorRangoDePeso">Buscar especie por rango de peso</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="EspecieMarina" asp-action="Index">Especies</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="EcosistemaMarino" asp-action="Index">Ecosistemas</a>
                            </li>




                        }
                        //No hay nadie logueado
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="EspecieMarina" asp-action="Index">Especies</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="EcosistemaMarino" asp-action="Index">Ecosistemas</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="EspecieMarina" asp-action="BuscarEspeciesEnPeligroDeExtincion">Especies en Peligro de Extincion</a>
                            </li>


                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="EspecieMarina" asp-action="BuscarEspeciesQueHabitanEcosistema">Buscar especies que habitan un ecosistema</a>
                            </li>


                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="EspecieMarina" asp-action="BuscarEcosistemasMarinosNoPuedenHabitarEspecie">Buscar ecosistemas marinos que no pueden habitar una especie</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="EspecieMarina" asp-action="BuscarPorNombreCientifico">Buscar especie por nombre cientifico</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="EspecieMarina" asp-action="BuscarPorRangoDePeso">Buscar especie por rango de peso</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Obligatorio_Cliente - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>